### PR TITLE
Use golang-starters/golang-rest-http in all go files

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR
 - Update the generated files in `app/` directory
 - Use golang-starters/golang-rest-http in all .go files

### CODE REVIEW

**Comment by sbose78** [comment]
I had added the `app` directory so that we could avoid adding the following not-so-standard commands in our s2i builder's assemble script. Checking in generated code - is not a wrong practice per se.

```
$(GOAGEN_BIN) app -d ${PACKAGE_NAME}/${DESIGN_DIR}
	$(GOAGEN_BIN) controller -d ${PACKAGE_NAME}/${DESIGN_DIR} -o controllers/ --pkg controllers --app-pkg ${PACKAGE_NAME}/app
	$(GOAGEN_BIN) gen -d ${PACKAGE_NAME}/${DESIGN_DIR} --pkg-path=github.com/fabric8-services/fabric8-common/goasupport/status --out app
```

How do you plan to handle this?

**Comment by sbose78** [comment]
> Use golang-starters/golang-rest-http in all .go files

Had missed this while moving the repo.
On a related note, this is special golang behaviour. For other boosters, repos are more of 'copy' 'paste' from booster org to user's org. In this case, we would need some sort of template-ization similar to https://github.com/fabric8-services/fabric8-starter in order to ensure that the import paths contain the user's org/profile. @jarifibrahim , that's a separate task though - the scope of your current work is to fix the builder image :)

**Comment by jarifibrahim** [comment]
> I had added the `app` directory so that we could avoid adding the following not-so-standard commands in our s2i builder's assemble script. Checking in generated code - is not a wrong practice per se.
> 
> ```
> $(GOAGEN_BIN) app -d ${PACKAGE_NAME}/${DESIGN_DIR}
> 	$(GOAGEN_BIN) controller -d ${PACKAGE_NAME}/${DESIGN_DIR} -o controllers/ --pkg controllers --app-pkg ${PACKAGE_NAME}/app
> 	$(GOAGEN_BIN) gen -d ${PACKAGE_NAME}/${DESIGN_DIR} --pkg-path=github.com/fabric8-services/fabric8-common/goasupport/status --out app
> ```
> How do you plan to handle this?

I had missed this and realized it when I tried to build it via S2I. I'll revert those commits :)

**Comment by jarifibrahim** [comment]
@sbose78 I've updated the PR. Can you please have another look?

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
